config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post "logout" => "users#logout"

  get 'posts/index' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show'
  post 'posts/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'
  
  resources :lessons
  
  get 'gallery' => 'home#gallery'
  get 'access' => 'home#access'
  get 'contact' => 'home#contact'
  post 'contact' => 'home#create'
  get 'thanks' => 'home#thanks'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    attr_accessor :name, :email, :tel, :content
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def authenticate_user
    if session[:user_id] == nil
      redirect_to("/")
    end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @posts = Post.all.order(created_at: :desc)
    @lessons = Lesson.all
  end
  
  def lesson
  end
  
  def gallary
  end
  
  def blog
  end
  
  def access
  end
  
  def contact
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(name: params[:name],tel: params[:tel],email: params[:email],content: params[:content])
      NotificationMailer.send_message(@contact).deliver_now
      redirect_to("/thanks")
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    def index
        @lessons = Lesson.all
    end
    
    def show
        @lesson = Lesson.find_by(id: params[:id])
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        @lesson = Lesson.new(title: params[:title],
                            subtitle: params[:subtitle],
                            content: params[:content],
                            price: params[:price],
                            image: params[:image])
        if @lesson.save
            redirect_to("/lessons/#{@lesson.id}")
        else
            render("lessons/new")
        end
    end
    
    def edit
        @lesson = Lesson.find_by(id: params[:id])
    end
    
    def update
        @lesson = Lesson.find_by(id: params[:id])
        @lesson.title = params[:title]
        @lesson.subtitle = params[:subtitle]
        @lesson.content = params[:content]
        @lesson.price = params[:price]
        @lesson.image = params[:image]
        if @lesson.save
            redirect_to("/lessons/#{@lesson}")
        else
            render("lessons/#{@lesson}")
        end
    end
    
    def destroy
        @lesson = Lesson.find_by(id: params[:id])
        @lesson.destroy
        redirect_to("/lessons")
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user,{only:[:new,:edit]}
  
  PER = 6
  def index
      @posts = Post.page(params[:page]).per(PER).order('created_at DESC')
  end
  
  def show
      @post = Post.find_by(id: params[:id])
  end
  
  def new
  end
  
  def create
      @post = Post.new(title: params[:title], content: params[:content], image: params[:image])
    if @post.save
      redirect_to("/posts/index")
    else
      render("posts/new")
    end
  end
  
  def edit
      @post = Post.find_by(id: params[:id])
  end
  
  def update
      @post = Post.find_by(id: params[:id])
      @post.title = params[:title]
      @post.content = params[:content]
      @post.image = params[:image]
      if @post.save
      redirect_to("/posts/index")
      else
      render("posts/edit")
      end
  end
  
  def destroy
      @post = Post.find_by(id: params[:id])
      @post.destroy
      redirect_to("/posts/index")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def login_form
    end
    
    def login
        @user = User.find_by(name: params[:name],password: params[:password])
        if @user
            session[:user_id] = @user.id
            redirect_to("/")
        else
            render("users/login_form")
        end
    end
    
    def logout
        session[:user_id] = nil
        redirect_to("/")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/contact.html.erb
<div class="bg2"><h1>Contact</h1></div>
<section>
  <div class="container wrapper">
    <div class="flex">
      <section class="form contact">
        <%= form_tag("/contact") do %>
        <h2>お問い合わせフォーム</h2>
          <div>
            <label for="name">お名前</label>
            <input type="text" id="name" name="name" required value="<%= @contact.name %>">
          </div>
          <div>
            <label for="tel">電話番号</label>
            <input id="tel" name="tel" required value="<%= @contact.tel %>">
          </div>
          <div>
            <label for="email">メールアドレス</label>
            <input type="email" id="email" required name="email" value="<%= @contact.email %>">
          </div>
          <div>
            <label for="content">内容</label>
            <textarea type="text" id="content" name="content" required><%= @contact.content %></textarea>
          </div>
          <div class="button">
            <button type="submit">送信</button>
          </div>
        <% end %>
      </section>
      
      <section class="contact">
        <h2>お支払いについて</h2>
        <p>初めての方は3日前までに指定の口座にお振込下さい。<br>
        2回目以降の方は振込み又は当日現金払いのどちらかでお願いします。</p>
        <h2>キャンセルポリシー</h2>
        <p>前日〜当日のキャンセルは受講料の全額をいただきます。<br>
        他の日に変更の場合はキャンセル料は発生しません。<br>
        一度お支払い頂いた受講費は、理由の如何にかかわらず返金致しかねます。</p>
        <br>
      </section>
    </div>
  
  <section class="qa contact">
    <div class="container">
      <h2>Q & A(よくあるご質問)</h2>
      <table>
        <tr>
          <th>Q.</th>
          <td>駐車場はありますか？</td>
        </tr>
        <tr>
          <th>A.</th>
          <td>専用の駐車場のご用意はありません。近くのコインパーキングをご案内しております。</td>
        </tr>
        <tr>
          <th>Q.</th>
          <td>誰でも受講できますか？</td>
        </tr>
        <tr>
          <th>A.</th>
          <td>自宅教室は女性限定ですが、同伴に限り男性も受講していただけます。</td>
        </tr>
        <tr>
          <th>Q.</th>
          <td>撮影はしても大丈夫ですか？</td>
        </tr>
        <tr>
          <th>A.</th>
          <td>レッスン中の撮影は、レッスン進行の妨げや他の方の迷惑にならない範囲でお願いします。</td>
        </tr>
      </table>
    </div>
  </section>
  </div>
</section>

app/views/home/gallery.html.erb
<div class="bg2"><h1>Instagram</h1></div>
<section>
      <div class="wrapper">
      <!-- InstaWidget -->
      <a href="https://instawidget.net/v/user/bellfieldsoap3" id="link-554c0a514501caab7424696699cd6ffdc7d3bc1df56d8bb2ac2f4869e9fbf5ba">@bellfieldsoap3</a>
      <script src="https://instawidget.net/js/instawidget.js?u=554c0a514501caab7424696699cd6ffdc7d3bc1df56d8bb2ac2f4869e9fbf5ba&width=100%"></script>
      </div>
</section>

app/views/home/thanks.html.erb
<div class="bg2"></div>
<section>
  <div id ="thanks">
    <h2>メッセージを送信しました。</h2>
    <p>お問い合わせ、お申し込み後2日以内に返信のない場合はお手数ですが、<br>
    直接お電話下さい。留守電の場合はお名前、お電話番号、<br>
    ご用件をお話し下さい。<br>こちらから折り返しご連絡させていただきます。</p>
    <p>メールアドレス:bellfieldsoap@gmail.com</p>
    <p>電話番号:090-5657-3143</p>
  </div>
</section>

app/views/home/top.html.erb
<div id="bg">
  <div id="top-text">
    <h1>手作り石けん教室</h1>
    <p>Bell field</p>
    <h2>手作り石けんから生まれる泡は、まるで繭から丁寧に作られた真綿のように、優しく包んでくれます。。。</h2>
  </div>
</div>

<!--About us-->
<section class="top-about-us top">
  <div class="container">
    <h1>About us</h1>
    <h3>手作り石けん教室Bell fieldでは、<br>コールドプロセス製法で<br>
    肌に優しい低刺激の石けんを作っています。<br>
    ビギナーさんを対象にした教室ですので、<br>
    石けん作りが初めての方や、<br>以前に作ったことはあるけど<br>
    また作りたいという方々にお越しいただいてます。<br>
    現在、全てのレッスンは単発制になっていますので、<br>
    作りたい時だけ受講していただけます。</h3>
    </div>
  </section>
  
<!--Instructor-->
<section class="top-instructor top">
    <h1>Instructor</h1>
    <img src="/images/soap7.jpg" alt="" width ="300" height="200">
    <h2>講師　藤原　裕子</h2>
    <img src="/images/handmade.png" alt="" width ="50" height="50" class="handmade-border">
    <P>一般社団法人　ハンドメイド石けん協会認定　<br>ジュニアソーパー<br>
    一般社団法人　ハンドメイド石けん協会認定　<br>犬の石けんマイスター</P>
</section>

<!--Lessons-->
<section class="top-lessons top">
  <div class="container">
    <h1>Lessons</h1>
    <div class="flex">
    <% if @lessons.present? %>
    <% @lessons[0..1].each do |lesson| %>
      <section class="top-lesson">
        <h2><%= lesson.title %></h2>
        <%= simple_format lesson.subtitle %>
        <%= image_tag lesson.image.url if lesson.image? %>
      </section>
     <% end %>
    </div>
    <div class="flex">
    <% @lessons[2..3].each do |lesson| %>
      <section class="top-lesson">
        <h2><%= lesson.title %></h2>
        <%= simple_format lesson.subtitle %>
        <%= image_tag lesson.image.url if lesson.image? %>
      </section>
     <% end %>
    </div>
    <% end %>
    <div class="flex">
      <section class="top-lesson top">
        <h2>1DAYレッスン</h2>
        <p>当教室で一番人気のレッスン。<br>
        甘い香りで癒され、洗い上がりもしっとり。</p>
        <img src="/images/soap8.jpg" alt="">
      </section>
    </div>
    <h3><%= link_to("講座一覧へ","/lessons",class: "border") %></h3>
  </div>
</section>

<!--Blog-->
<section class="top-articles top">
  <div class="container">
    <h1>Articles</h1>
    <div class="flex">
      <% if @posts.present? %>
      <% @posts[0..1].each do |post| %>
      <section class="top-article">
        <%= image_tag post.image.url if post.image? %>
        <h2><%= post.title %></h2>
        <p><%= link_to("記事詳細へ","/posts/#{post.id}",class: "border") %></p>
      </section>
      <% end %>
    </div>
    
    <div class="flex">
      <% @posts[2..3].each do |post| %>
      <section class="top-article">
        <%= image_tag post.image.url if post.image? %>
        <h2><%= post.title %></h2>
        <p><%= link_to("記事詳細へ","/posts/#{post.id}",class: "border") %></p>
      </section>
      <% end %>
    </div>
    <% end %>
  </div>
</section>

<!--Feed back-->
<section class="top-feedback top">
  <div class="container">
    <h1>Feedback</h1>
    <div class="flex">
      <section class="voice">
        <img src="/images/soap6.jpg" alt="">
        <h2>利用者の声</h2>
        <p>楽しかったです。楽しかったです</p>
      </section>
      <section class="voice">
        <img src="/images/soap7.jpg" alt="">
        <h2>利用者の声</h2>
        <p>楽しかったです。楽しかったです</p>
      </section>
      <section class="voice">
        <img src="/images/soap8.jpg" alt="">
        <h2>利用者の声</h2>
        <p>楽しかったです。楽しかったです。</p>
      </section>
    </div>
  </div>
</section>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  
  <title>手作り石けん教室　Bell field</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header id="luxbar" class="luxbar-fixed">
  <input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/>
  <div class="luxbar-menu luxbar-menu-right luxbar-menu-light">
      <ul class="luxbar-navigation">
          <li class="luxbar-header">
            <%= link_to image_tag("/images/logo.png"), "/"%>
              <label class="luxbar-hamburger luxbar-hamburger-doublespin" 
              id="luxbar-hamburger" for="luxbar-checkbox"> <span></span> </label>
          </li>
          <% if session[:user_id] %>
          <li class="luxbar-item"><%= link_to("講座作成","/lessons/new") %></li>
          <li class="luxbar-item"><%= link_to("新規投稿","/posts/new") %></li>
          <li class="luxbar-item"><%= link_to("ログアウト","/logout",{method: :post}) %></li>
          <% end %>
          <li class="luxbar-item"><%= link_to("HOME","/") %></li>
          <li class="luxbar-item"><%= link_to("LESSONS","/lessons") %></li>
          <li class="luxbar-item"><%= link_to "GALLERY","/gallery", 'data-turbolinks': false %></li>
          <li class="luxbar-item"><%= link_to("ARTICLES","/posts/index") %></li>
          <li class="luxbar-item"><%= link_to("CONTACT","/contact") %></li>
      </ul>
  </div>
  </header>

  <%= yield %>
    
  <footer>
      <nav>
        <ul class="clearfix">
          <li><%= link_to("HOME","/") %></li>
          <li><%= link_to("LESSONS","/lessons") %></li>
          <li><%= link_to"GALLERY","/gallery", 'data-turbolinks': false %></li>
          <li><%= link_to("ARTICLES","/posts/index") %></li>
          <li><%= link_to("CONTACT","/contact") %></li>
        </ul>
      </nav>
      <nav>
        <ul class="clearfix">
          <p><%= link_to("©︎2018　Bell field","/login") %></p>
        </ul>
      </nav>
  </footer>
</body>
</html>

app/views/lessons/edit.html.erb
<div class="bg2"><h1>レッスン編集</h1></div>
<section class="lesson form new">
  <div class="container">
    <%= form_tag("/lessons/#{@lesson.id}",{multipart: true,method: "patch"}) do %>
      <div>
        <%= label_tag :image,"写真" %><br>
        <%= file_field_tag :image, accept: 'image/jpeg,image/gif,image/png' %><br>
      </div>
      <div>
        <label for="title">タイトル</label>
        <input id="title" name="title" value="<%= @lesson.title %>">
      </div>
       <div>
        <label for="subtitle">サブタイトル</label>
        <textarea id="subtitle" name="subtitle"><%= @lesson.subtitle %></textarea>
      </div>
      <div>
        <label for="content">本文</label>
        <textarea  name="content"><%= @lesson.content %></textarea>
      </div>
      <div>
        <label for="price">受講費</label>
        <input id ="price" name="price" value="<%= @lesson.price %>">
      </div>
      <div class="button">
        <button type="submit">編集</button>
      </div>
    <% end %>
  </div>
</section>

app/views/lessons/index.html.erb
<div class="bg2"><h1>Lessons</h1></div>
<section>
  <div class="container wrapper">
    <div class="flex">
      <section class="lessons">
        <table>
          <h2>レッスン一覧</h2>
          <% @lessons[0..3].each do |lesson| %>
          <tr>
            <th>・</th>
            <td><%= link_to lesson.title , lesson_path(lesson) %></td>
          </tr>
          <% end %>
          <tr>
            <th>・</th>
            <td>1DAYレッスン</td>
          </tr>
          <% @lessons.each do |lesson| %>
          <tr>
            <th></th>
            <td><%= link_to lesson.title , lesson_path(lesson) %></td>
          </tr>
          <% end %>
        </table>
      </section>
      <section class="lessons">
        <table>
          <h2>全てのレッスンの共通事項</h2>
          <tr>
            <th>場所</th>
            <td>自宅教室(兵庫県伊丹市)お申し込み後<br>メールにて詳細をお知らせします。</td>
          </tr>
          <tr>
            <th>日時</th>
            <td>ご希望の日時で調整させていただきます。</td>
          </tr>
          <tr>
            <th>人数</th>
            <td>1名〜4名の少人数制</td>
          </tr>
          <tr>
            <th>所要時間</th>
            <td>1時間半〜2時間程度</td>
          </tr>
          <tr>
            <th>持ち物</th>
            <td>ゴム手袋※①、メガネ※②、型※③、マスク、<br>エプロン、保冷バッグ、古タオル、筆記用具</td>
            </tr>
          <tr>
            <th>※・・・</th>
            <td>①花粉眼鏡など目を覆えるもの。<br>
            (なければ教室用をお貸しできます。)<br>
            日常で眼鏡をおかけの方は必要ありません。<br>
            ②手にフィットするものが作業しやすいです。<br>
            ③初めての方はこちらで準備します。
            </td>
          </tr>
            <tr>
              <th></th>
              <td>特に明記のないものは250ｇバッチで作ります。<br>(4〜5個の石けんができます。)
              <br><br>精油は100滴(5ml)までお使いいただけます。</td>
            </tr>
        </table>
      </section>
    </div>
  </div>
</section>

app/views/lessons/new.html.erb
<div class="bg2"><h1>Lesson new</h1></div>
<section>
  <div class="container wrapper new">
    <%= form_tag("/lessons",{multipart: true}) do %>
      <div>
        <%= label_tag :image,"写真" %><br>
        <%= file_field_tag :image, accept: 'image/jpeg,image/gif,image/png.image/jpg' %><br>
      </div>
      <div>
        <label for="title">タイトル</label>
        <input id="title" name="title">
      </div>
       <div>
        <label for="subtitle">サブタイトル</label>
        <textarea id="subtitle" name="subtitle"></textarea>
      </div>
      <div>
        <label for="content">本文</label>
        <textarea  name="content"></textarea>
      </div>
      <div>
        <label for="price">受講費</label>
        <input id ="price" name="price">
      </div>
      <div class="button">
        <button type="submit">編集</button>
      </div>
    <% end %>
  </div>
</section>

app/views/lessons/show.html.erb
<div class="bg2"><h1>Lesson</h1></div>
<section>
   <div class="container wrapper">
     <div class="flex">
       <section class="lessons center">
        <h2><%= @lesson.title %></h2>
        <p class="left"><%= simple_format @lesson.content %></p>
        <p>受講費<%= @lesson.price %></p>
        <%= image_tag @lesson.image.url if @lesson.image? %>
        <% if session[:user_id] %>
          <p><%= link_to "編集","/lessons/#{@lesson.id}/edit" %>
          <%= link_to "削除","/lessons/#{@lesson.id}", {method: "delete"} %></p>
        <% end %>
      </section>
      
      <section class="form contact">
        <%= form_tag("/contact") do %>
        <h2>お問い合わせフォーム</h2>
          <div>
            <label for="name">お名前</label>
            <input type="text" id="name" name="name" required>
          </div>
          <div>
            <label for="tel">電話番号</label>
            <input id="tel" name="tel" required>
          </div>
          <div>
            <label for="email">メールアドレス</label>
            <input type="email" id="email" required>
          </div>
          <div>
            <label for="content">内容</label>
            <textarea type="text" id="content" name="content" required></textarea>
          </div>
          <div class="button">
            <button type="submit">送信</button>
          </div>
        <% end %>
      </section>
    </div>
  </div>
</section>

app/views/posts/edit.html.erb
<div class="bg2"><h1>編集</h1></div>
<section>
  <div class="container wrapper new">
    <%= form_tag("/posts/#{@post.id}/update",{multipart: true}) do %>
      <div>
        <label for="image">画像</label>
        <%= file_field_tag :image, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
      <div>
        <label for="title">タイトル</label>
        <textarea id="title" name="title"><%= @post.title %></textarea>
      </div>
      <div>
        <label for="content">本文</label>
        <textarea id ="content" name="content"><%= @post.content %></textarea>
      </div>
      <div class="button">
        <button type="submit">編集</button>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/index.html.erb
<div class="bg2"><h1>Articles</h1></div>
<section>
  <div class="container wrapper">
    <div class="flex">
      <% @posts.each do |post| %>
        <section class="post">
          <%= image_tag post.image.url if post.image? %>
          <h2><%= post.title %></h2>
          <%= link_to("記事をみる","/posts/#{post.id}",class: "border") %>
        </section>
      <% end %>
      
      <% if @posts.length > 6 %>
      <%= link_to("次ページへ","/posts/index") %>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</section>

app/views/posts/new.html.erb
<div class="bg2"><h1>新規投稿</h1></div>
<section>
  <div class="container wrapper new">
    <%= form_tag("/posts/create",{multipart: true}) do %>
      <div>
        <label for="image">画像</label>
        <%= file_field_tag :image, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
      <div>
        <label for="title">タイトル</label>
        <textarea id="title" name="title"></textarea>
      </div>
      <div>
        <label for="content">本文</label>
        <textarea id ="content" name="content"></textarea>
      </div>
      <div class="button">
        <button type="submit">投稿</button>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<div class="bg2"><h1>Article</h1></div>
<section>
  <div class="container wrapper post">
      <%= image_tag @post.image.url if @post.image? %>
      <h2><%= @post.title %></h2>
      <%= simple_format(@post.content) %>
      <% if session[:user_id] %>
      <%= link_to("編集","/posts/#{@post.id}/edit") %>
      <%= link_to("削除", "/posts/#{@post.id}/destroy", {method: "post"}) %>
      <% end %>
  </div>
</section>

app/views/users/login_form.html.erb
<div class="bg2"><h1>Login</h1></div>
<%= form_tag("/login") do %>
<div id="login_form">
  <p>名前</p>
  <input name="name">
  <p>パスワード</p>
  <input type="password" name="password">
  <P>ログイン</P>
  <button type="submit">送信</button>
</div>
<% end %>